# Generated by Django 5.1.7 on 2025-03-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_description', models.TextField()),
                ('event_date', models.DateTimeField()),
                ('event_locate', models.CharField(blank=True, max_length=50)),
                ('event_category', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
