# Generated by Django 5.1.7 on 2025-03-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=30)),
                ('book_author', models.CharField(max_length=50)),
                ('book_publication_date', models.DateTimeField()),
                ('book_category', models.CharField(choices=[('AC', 'Action'), ('RO', 'Romance'), ('FI', 'Fiction')], default='ACTION', max_length=3)),
            ],
            options={
                'verbose_name_plural': 'Books',
            },
        ),
    ]
