# Generated by Django 5.1.7 on 2025-03-07 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_category',
            field=models.CharField(choices=[('AC', 'Action'), ('RO', 'Romance'), ('FI', 'Fiction')], default='Action', max_length=3),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_publication_date',
            field=models.IntegerField(),
        ),
    ]
