# Generated by Django 5.2 on 2025-04-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('strength', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('agility', models.IntegerField()),
                ('abilities', models.CharField(max_length=40)),
            ],
        ),
    ]
