# Generated by Django 5.1.7 on 2025-05-08 16:21

import django.db.models.deletion
import teacher_track.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_track', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='nif',
        ),
        migrations.AlterField(
            model_name='account',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='teacher_track.subject'),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that nif already exists.'}, help_text='Required. 10 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=10, unique=True, validators=[teacher_track.models.MyValidator()], verbose_name='nif'),
        ),
    ]
