# Generated by Django 5.1.7 on 2025-03-07 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0002_alter_book_book_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_publication_date',
            field=models.CharField(max_length=10),
        ),
    ]
